os: osx
osx_image: xcode8
sudo: false
language: objective-c

env:
  matrix:
    - NODE_VERSION="4" NPM_VERSION=3
    - NODE_VERSION="5" NPM_VERSION=3
    - NODE_VERSION="5" NPM_VERSION=4
    - NODE_VERSION="6" NPM_VERSION=3
    - NODE_VERSION="6" NPM_VERSION=4

script:
  - npm install
  - npm run build
  - npm run test
before_install:
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install -g npm@$NPM_VERSION
  - brew update > /dev/null;
  - brew install jpeg python3 imagemagick
  # Show environment invo
  - node --version
  - npm --version
